name: build

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: xcode info
      run: xcodebuild -version
    - name: carthage
      run: arch -x86_64 /usr/local/bin/brew install carthage
    - name: carthage info
      run: |
        carthage version
        which carthage
        lipo -archs $(which carthage)
    - name: older
    - name: xprojup install
      run: curl -sL https://phimage.github.io/xprojup/install.sh | bash
    - name: setup rosetta
      run: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    - name: carthage
      run: ./build.sh
